/**
 * Service to load scraped properties from the data directory
 * These properties are generated by the daily GitHub Actions scraper
 */

import { Property } from '../types';

const SCRAPED_DATA_URL = '/data/scraped_properties.json';

/**
 * Load scraped properties from the JSON file
 */
export async function loadScrapedProperties(): Promise<Property[]> {
    try {
        const response = await fetch(SCRAPED_DATA_URL);

        if (!response.ok) {
            console.log('[ScrapedData] No scraped properties file found');
            return [];
        }

        const data = await response.json();

        if (!Array.isArray(data)) {
            console.warn('[ScrapedData] Invalid data format');
            return [];
        }

        console.log(`[ScrapedData] Loaded ${data.length} scraped properties`);
        return data as Property[];

    } catch (error) {
        console.error('[ScrapedData] Error loading scraped properties:', error);
        return [];
    }
}

/**
 * Get count of pending properties from scraped data
 */
export function countPendingProperties(properties: Property[]): number {
    return properties.filter(p => p.approvalStatus === 'pending').length;
}

/**
 * Get the last scrape date from properties
 */
export function getLastScrapeDate(properties: Property[]): Date | null {
    const scrapedDates = properties
        .filter(p => (p as any).scrapedAt)
        .map(p => new Date((p as any).scrapedAt));

    if (scrapedDates.length === 0) return null;

    return new Date(Math.max(...scrapedDates.map(d => d.getTime())));
}
